### ISSUE TITLE
per-icon viewBox attributes lost in translation

### ISSUE THREAD

**Issue by benswift** [sylvainmetayer/jekyll-fontawesome-svg#11]
Hey there

I was returning to this gem after a while (see #5) and I think I've got a bit further in figuring out what my issue is.

All of the FA icons have a `viewBox` attribute which defines the size of the outermost path (_approx_ `0 0 512 512`, but differs for each icon). However, this library spits the svg path data into an element with a [fixed `viewBox` size of `0 0 1024 1024`](https://github.com/sylvainmetayer/jekyll-fontawesome-svg/blob/master/lib/jekyll/fontawesome/svg/fa-icon.rb#L43). This means that when sizing the icons (e.g. with CSS `height` and `width` there's just a bunch of empty space in the bottom right---and that makes alignment, etc. a pain.

So, is there a reason we can't spit the `viewBox` attribute into the output HTML?

Relatedly, is there a reason that this lib uses a `<symbol>` element for the icon instead of just an `<svg>`? If we just used an svg, the regex-finding-path stuff wouldn't be necessary---you could just insert the `.svg` file contents straight in.

If you like, I'm happy to do the work and submit a pull request, but I just wanted to check first.

**Comment by benswift** [comment]
Re: `<symbol>`, [I think I understand that part now](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol). But it would still be nice if we could actually retain the proper `viewBox` data rather than just the hardcoded `0 0 1024 1024`.

**Comment by sylvainmetayer** [comment]
Hello,

> So, is there a reason we can't spit the viewBox attribute into the output HTML?

No, their is no reason and I can't remember why I did this this way. The behaviour should indeed be getting back the viewbox per icon, not define a hardcoded one. 

I can take a look at it next week but if you want to submit a PR, I'll gladly accept it and merge it before the end of the week!

**Comment by benswift** [comment]
Ok, great :) I did end up fixing it, it’s in my fork. I’m on mobile atm, but will create a pull request ASAP.

**Comment by sylvainmetayer** [comment]
Fix available with [v3.0.1](https://rubygems.org/gems/jekyll-fontawesome-svg/versions/0.3.1), thanks !

**Comment by benswift** [comment]
Nice one. Eventually, you could switch to [nokogiri](https://nokogiri.org) (which is a Jekyll dep anyway) to make life easier with the HTML munging, but the regex thing is fine for now.
