### ISSUE TITLE
This plugin doesn't work without github-pages gem

### ISSUE THREAD

**Issue by heychirag** [sylvainmetayer/jekyll-fontawesome-svg#15]
I have added this plugin to my Gemfile and also did a bundle install, but I get the following message:

```
Requiring backports/<ruby version> is deprecated. Require just the needed backports instead
Rails backports are deprecated.
Configuration file: _config.yml
Configuration file: _config-dev.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-fontawesome-svg or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-fontawesome-svg' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
jekyll 3.8.5 | Error:  jekyll-fontawesome-svg
```

But surprisingly everything works fine with the `github-pages` gem installed. But the point is I don't want to use `github-pages` because I am using Gitlab instead. And `github-pages` plugin throws a host of other errors on Gitlab runners.

**Comment by sylvainmetayer** [comment]
Hello,

Sorry you're having issue with this. The `github-pages` gem should only be included if their is a `GH_PAGES` environment variable defined. Is their any chance that Gitlab page use the same environment variables ?

**Comment by jayloofah** [comment]
I am having the same issue while hosting on Gitlab - is the ```github-pages``` gem necessary?

**Comment by sylvainmetayer** [comment]
The `githu-pages` is necessary for histing site with github page. I haven't tried to deploy it on gitlab pages, can you give me a link to your repo, so I can try to see what I can do ?

**Comment by heychirag** [comment]
@sylvainmetayer here is mine: https://gitlab.com/heychirag/heychirag.gitlab.io

**Comment by heychirag** [comment]
Hi @sylvainmetayer @jayloofah I have found a temporary solution to this for Gitlab. Add this to your `.gitlab-ci.yml`

```
pages:
    script:
        - export PAGES_REPO_NWO=<username>/<reponame>
```

`<username>/<reponame>` could be totally random or probably has to point to a real repo on Github. Try both ways, one should definitely work. This is actually what the `github-pages` gem was complaining about since it wasn't able to extract this info from the remote name in `.git` folder. Once it get's this info, it builds flawlessly.

**Comment by jayloofah** [comment]
@heychirag , I found that solution as well just by adding ```repository: test/test``` in the config.yml. But I guess I was just curious why this gem requires github-pages itself? It could do without it couldn't it?

**Comment by sylvainmetayer** [comment]
Hello @jayloofah 

You're right, it shouldn't not require `github-pages` as this gem is not compatible with it. I'll remove it and publish a new version soon (before the end of the week).

**Comment by sylvainmetayer** [comment]
Done in v0.3.3

**Comment by jayloofah** [comment]
Sorry to reopen.

There might be something wrong with either my configuration or the way dependencies are installed the site will not build due to missing dependencies (if one build without the github-pages gem).

Is it possible that you need to add some dependency that was included within the github gem?

**Comment by sylvainmetayer** [comment]
Can you provide more details and context about what dependency are missing please?

**Comment by jayloofah** [comment]
The error message doesn't mention which dependency I'm missing. The only thing I changed was removing the `gh-pages` gem and the site would not build. I'm hosting on GitLab so there's no issue with 3rd party plugins that I know of.

**Comment by jacksonmgoode** [comment]
<img width="751" alt="Screenshot 2020-08-28 at 23 58 58" src="https://user-images.githubusercontent.com/54308792/91618367-b0845a80-e979-11ea-855e-f7ce35feeb8b.png">

Here is the error, that only appears when the "github-pages: gem is removed from the gemfile.

**Comment by jacksonmgoode** [comment]
Just discovered the issue! It had something to do with Jekyll 4 perhaps? Once I upgraded I was able to remove the GitHub gem all together.

**Comment by sylvainmetayer** [comment]
How did you create your site with Gitlab pages, did you used gitlab CI ? Is your repository public so I can take a look at what could be missing in my plugin definition in the job's logs ?

**Comment by sylvainmetayer** [comment]
Closed due to inactivity, feel free to reopen with additional context if needed.
