### ISSUE TITLE
Some icons do not work - cache is too old?

### ISSUE THREAD

**Issue by cloudscalebytes** [sylvainmetayer/jekyll-fontawesome-svg#30]
Hi, thx for the easy to use library.   Is it possible to refresh the cache of icons please?
One example that is not present: https://fontawesome.com/icons/hourglass-half?s=regular&f=classic

**Comment by sylvainmetayer** [comment]
Hi, I haven't updated this gem in a while, as I don't use Jekyll anymore.

The icons are outdated, but can be updated by replacing in this folder all the icons with the latest version of icons https://github.com/sylvainmetayer/jekyll-fontawesome-svg/tree/master/lib/jekyll/fontawesome/svg/assets/fa_svgs 

I'll try to do it during the holidays but can't promise anything. However, if you want to submit a PR, I'll review it and merge it.

**Comment by sylvainmetayer** [comment]
Fixed with #32

**Comment by cloudscalebytes** [comment]
> Fixed with #32

Works great, thanks for the fix.
